---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: lcrown/hpc-cmdb-api
        ports:
          - containerPort: 8000
            name: api
        env:
          - name: DB_USERNAME
            value: admin
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: db-password
                optional: false
