FROM python:3.10

ENV DB_USERNAME DB_USERNAME
ENV DB_PASSWORD DB_PASSWORD

WORKDIR /api

COPY ./requirements.txt /api/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /api/requirements.txt

COPY ./main.py /api/main.py

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
